name = "DefintionInProgram"
version = "0.1.0"
defaultTargets = ["DefintionInProgram"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true
# relaxedAutoImplicit = false

[[require]]
name = "mathlib"

[[require]]
name = "iris"
git.url = "https://github.com/leanprover-community/iris-lean.git"
git.subDir = "Iris"
rev = "391b22c69f63169c3b1c9dbb0ff736ebeef6514f"


[[lean_lib]]
name = "ITree"
globs = ["ITree", "ITree.+"]

[[lean_lib]]
name = "Paco"
globs = ["Paco", "Paco.+"]

[[lean_lib]]
name = "ProgramLogicCarte"
globs = ["ProgramLogicCarte", "ProgramLogicCarte.+"]

[[lean_lib]]
name = "DefinitionInProgramLib"
globs = ["DefintionInProgram.+"]

[[lean_exe]]
name = "DefintionInProgram"
root = "Main"
